[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "glimepiride-model"
version = "0.6.3"
description = "Python code for glimepiride-model"
readme = "README.md"
requires-python = ">=3.14"
authors = [
    {name="Michelle Elias", email="michelleelias66@gmail.com"},
	{name="Matthias König", email="konigmatt@googlemail.com"},
]
maintainers = [
	{name="Matthias König", email="konigmatt@googlemail.com"}
]
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Science/Research",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
    "Programming Language :: Python :: 3.14",
	"Programming Language :: Python :: Implementation :: CPython",
	"Topic :: Scientific/Engineering",
	"Topic :: Scientific/Engineering :: Bio-Informatics",
]
keywords = [
    "digital twin",
    "diabetes",
    "Glimepiride",
    "PBPK",
    "physiologically based pharmacokinetic model",
]
dependencies = [
    "sbmlutils>=0.9.6",
    "sbmlsim @ git+https://github.com/matthiaskoenig/sbmlsim.git@4c0515664a3a5b535ab83534949d45cd25f30e22"
]
[project.scripts]
create_nodes = "pkdb_data.management.commands:create_info_nodes_command"
fit_glimepiride = "pkdb_models.models.glimepiride.fitting.fitting:main"
run_glimepiride = "pkdb_models.models.glimepiride.run_glimepiride:main"

[project_urls]
Homepage = "https://github.com/matthiaskoenig/glimepiride-model"
Repository = "https://github.com/matthiaskoenig/glimepiride-model"
Documentation = "https://github.com/matthiaskoenig/glimepiride-model"
Issues = "https://github.com/matthiaskoenig/glimepiride-model/issues"
# Download = "https://pypi.org/project/pkdb_data"

[tool.hatch.build.targets.wheel]
packages = ["src/pkdb_models"]

[tool.hatch.metadata]
allow-direct-references = true