from pathlib import Path

GLIMEPIRIDE_PATH = Path(__file__).parent

MODEL_BASE_PATH = GLIMEPIRIDE_PATH / "models" / "results" / "models"
MODEL_PATH = MODEL_BASE_PATH / "glimepiride_body_flat.xml"

RESULTS_PATH = GLIMEPIRIDE_PATH / "results"
RESULTS_PATH_SIMULATION = RESULTS_PATH / "simulation"
RESULTS_PATH_ANALYSES = RESULTS_PATH / "cyp2c9_analyses"
RESULTS_PATH_FIT = RESULTS_PATH / "fit"

# DATA_PATH_BASE = GLIMEPIRIDE_PATH.parents[3] / "pkdb_data" / "studies"
DATA_PATH_BASE = GLIMEPIRIDE_PATH / "data"

DATA_PATH_GLIMEPIRIDE = DATA_PATH_BASE / "glimepiride"
DATA_PATH_DAPAGLIFLOZIN = DATA_PATH_BASE / "dapagliflozin"
DATA_PATHS = [
     DATA_PATH_GLIMEPIRIDE,
     DATA_PATH_DAPAGLIFLOZIN,
]
