name: Build and Run Docker Container

on: [push]

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Build Docker image
#        run: docker build -t matthiaskoenig/glimepiride .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: cicd
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run command in container
        run: docker run --rm cicd run_glimepiride -a all -r /results